# Generated by Django 4.0.6 on 2022-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_reader_authors_reader_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='genres',
            field=models.CharField(default='Fiction', max_length=225),
            preserve_default=False,
        ),
    ]
